package Employee;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.*;

public class Tasks extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    
    public Tasks()  {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Abc ob = new Abc();
        ob.start();
//       String a=(Login.Login.t1.getText());
//       id.setText("Welcome"+a);
    }
    public Tasks(String userid)  {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Abc ob = new Abc();
        ob.start();
//       String a=(Login.Login.t1.getText());
      id.setText("Welcome "+userid);
    }
    

    class Abc extends Thread {

        public void run() {
            while (true) {
                java.util.Date dt = new java.util.Date();
                String cdate = (dt.getYear() + 1900) + "-" + (dt.getMonth() + 1) + "-" + dt.getDate() + " "
                        + dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
                lbltime.setText(cdate);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewCustomerAcc = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        Withdraw = new javax.swing.JButton();
        CustomerAccountDetails = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        DeleteCusAcc = new javax.swing.JButton();
        History = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        NewEmployeeAccount = new javax.swing.JButton();
        lbltime = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NewCustomerAcc.setBackground(new java.awt.Color(153, 153, 255));
        NewCustomerAcc.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        NewCustomerAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        NewCustomerAcc.setText("New Customer Account");
        NewCustomerAcc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NewCustomerAcc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NewCustomerAcc.setIconTextGap(14);
        NewCustomerAcc.setMargin(new java.awt.Insets(4, 16, 4, 16));
        NewCustomerAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerAccActionPerformed(evt);
            }
        });
        getContentPane().add(NewCustomerAcc);
        NewCustomerAcc.setBounds(100, 140, 310, 110);

        Deposit.setBackground(new java.awt.Color(0, 204, 102));
        Deposit.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Deposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deposit.png"))); // NOI18N
        Deposit.setText("Deposit");
        Deposit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Deposit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Deposit.setIconTextGap(50);
        Deposit.setMargin(new java.awt.Insets(4, 16, 4, 16));
        Deposit.setPreferredSize(new java.awt.Dimension(95, 23));
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });
        getContentPane().add(Deposit);
        Deposit.setBounds(900, 280, 330, 110);

        Withdraw.setBackground(new java.awt.Color(204, 255, 204));
        Withdraw.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/withdraw 1.png"))); // NOI18N
        Withdraw.setText("Withdraw");
        Withdraw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Withdraw.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Withdraw.setIconTextGap(50);
        Withdraw.setMargin(new java.awt.Insets(4, 16, 4, 16));
        Withdraw.setPreferredSize(new java.awt.Dimension(95, 23));
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(Withdraw);
        Withdraw.setBounds(900, 140, 330, 110);

        CustomerAccountDetails.setBackground(new java.awt.Color(51, 153, 255));
        CustomerAccountDetails.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 15)); // NOI18N
        CustomerAccountDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accountdetails.jpg"))); // NOI18N
        CustomerAccountDetails.setText("Customer Account details");
        CustomerAccountDetails.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerAccountDetails.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        CustomerAccountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerAccountDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerAccountDetails);
        CustomerAccountDetails.setBounds(100, 420, 310, 105);

        Update.setBackground(new java.awt.Color(255, 153, 153));
        Update.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateicon.png"))); // NOI18N
        Update.setText("Update");
        Update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Update.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Update.setIconTextGap(50);
        Update.setMargin(new java.awt.Insets(4, 16, 4, 16));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(490, 280, 330, 110);

        DeleteCusAcc.setBackground(new java.awt.Color(204, 255, 204));
        DeleteCusAcc.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 15)); // NOI18N
        DeleteCusAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteicon.png"))); // NOI18N
        DeleteCusAcc.setText("Delete Customer Account");
        DeleteCusAcc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DeleteCusAcc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DeleteCusAcc.setIconTextGap(7);
        DeleteCusAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCusAccActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteCusAcc);
        DeleteCusAcc.setBounds(490, 420, 330, 105);

        History.setBackground(new java.awt.Color(255, 153, 0));
        History.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history.png"))); // NOI18N
        History.setText("Transaction History");
        History.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        History.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        History.setIconTextGap(15);
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });
        getContentPane().add(History);
        History.setBounds(900, 420, 330, 105);

        Transfer.setBackground(new java.awt.Color(0, 204, 255));
        Transfer.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        Transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaction.png"))); // NOI18N
        Transfer.setText("Transfer");
        Transfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Transfer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Transfer.setIconTextGap(50);
        Transfer.setMargin(new java.awt.Insets(4, 16, 4, 16));
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(100, 280, 310, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mybank.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(495, 11, 348, 78);

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setText("Welcome Id ");
        getContentPane().add(id);
        id.setBounds(560, 100, 200, 40);

        NewEmployeeAccount.setBackground(new java.awt.Color(204, 0, 51));
        NewEmployeeAccount.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 15)); // NOI18N
        NewEmployeeAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empic.png"))); // NOI18N
        NewEmployeeAccount.setText("New Employee Account");
        NewEmployeeAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NewEmployeeAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        NewEmployeeAccount.setMargin(new java.awt.Insets(4, 16, 4, 16));
        NewEmployeeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewEmployeeAccountActionPerformed(evt);
            }
        });
        getContentPane().add(NewEmployeeAccount);
        NewEmployeeAccount.setBounds(490, 140, 330, 110);

        lbltime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltime.setForeground(new java.awt.Color(255, 102, 102));
        lbltime.setText("date and time");
        getContentPane().add(lbltime);
        lbltime.setBounds(900, 30, 220, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(0, 0, 1, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1203, 11, 60, 60);

        jButton7.setBackground(new java.awt.Color(102, 255, 153));
        jButton7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bal.png"))); // NOI18N
        jButton7.setText("Balance");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.setIconTextGap(30);
        jButton7.setMargin(new java.awt.Insets(0, 0, 2, 1));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(100, 550, 310, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bk.jpg"))); // NOI18N
        jLabel3.setText("background");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1660, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
        Task.Withdraw ob4 = new Task.Withdraw();
        ob4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_WithdrawActionPerformed

    private void NewCustomerAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerAccActionPerformed
        Task.CuAcc ob = new Task.CuAcc();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewCustomerAccActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        Task.Deposit ob3 = new Task.Deposit();
        ob3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DepositActionPerformed

    private void NewEmployeeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewEmployeeAccountActionPerformed
        Task.EmployeeAcc ob1 = new Task.EmployeeAcc();
        ob1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewEmployeeAccountActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        Task.Transfer ob5 = new Task.Transfer();
        ob5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransferActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Task.UpdateC ob6 = new Task.UpdateC();
        ob6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateActionPerformed

    private void CustomerAccountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerAccountDetailsActionPerformed
        Task.CustomerInfo ob7 = new Task.CustomerInfo();
        ob7.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CustomerAccountDetailsActionPerformed

    private void DeleteCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCusAccActionPerformed
        Task.Delete_Acc ob = new Task.Delete_Acc();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeleteCusAccActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Login.Login ob8 = new Login.Login();
        ob8.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
       Task.History ob=new Task.History();
       ob.setVisible(true);
       this.setVisible(false);

    }//GEN-LAST:event_HistoryActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Task.BalanceEnq ob = new Task.BalanceEnq();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerAccountDetails;
    private javax.swing.JButton DeleteCusAcc;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton History;
    private javax.swing.JButton NewCustomerAcc;
    private javax.swing.JButton NewEmployeeAccount;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton Update;
    private javax.swing.JButton Withdraw;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbltime;
    // End of variables declaration//GEN-END:variables
}
